### ISSUE TITLE
'transform' command modifies module dependency reference set files

### ISSUE THREAD

**Issue by apeteri** [b2ihealthcare/rf2-d2#6]
Running a transformation on an existing release .zip with eg. the example script on the [documentation page](https://docs.b2i.sg/rf2-d2/commands/transform) also modifies module dependency reference set files if any of the last two columns, `sourceEffectiveTime` and `targetEffectiveTime` contain blanks:

```bash
$ rf2 transform SnomedCT_RF2_PRODUCTION_20190131T120000Z.zip \
"effectiveTime = 'Concept'.equals(_file.getType()) ? '20190201' : effectiveTime"
```

Resulting output:
```
[...]
Started Transforming '/path/to/Full/Refset/Metadata/der2_ssRefset_ModuleDependencyFull_<ns>_<effectiveTime>.txt'
Total lines: '472'
Modified lines: '8'
Finished Transforming '/path/to/Full/Refset/Metadata/der2_ssRefset_ModuleDependencyFull_<ns>_<effectiveTime>.txt' [2.582 ms]
[...]
```

**Comment by cmark** [comment]
Thank you for reporting the issue @apeteri! Fixed in 7d3df29. Will be available in the next 0.4.0 release.
